AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'Gemfile'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/DoubleNegation:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/SymbolArray:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Layout/IndentFirstArgument:
  EnforcedStyle: consistent

Rails/DynamicFindBy:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Documentation:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - app/views/**/*
    - spec/**/*
    - 'app/views/**/*.jbuilder'
  Max: 120

Metrics/BlockLength:
  Exclude:
     - 'Rakefile'
     - '**/*.rake'
     - 'spec/**/*.rb'
     - 'app/views/**/*.jbuilder'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
  SupportedStyles:
    - aligned
    - indented

Metrics/AbcSize:
  Enabled: true
  Max: 20

Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 20
  Exclude:
  - "spec/**/*"

